description: Provides a user interface for the user to upload an image file. Outputs
  the uploaded image filename and content in base64 format along with the file format.
  The component accepts image files with common formats (JPG, PNG, GIF, etc.). Once
  the user uploads the image, it is converted to a base64-encoded string and returned
  with the filename and file format.
name: ImageUploader
parameters: {}
