description: Applies the suggested edits from AIModel to the input image, generating
  an enhanced image preview. Outputs the enhanced image, its filename, and file format.
name: ImageEditor
parameters: {}
